name: Release Kakoune Bundle

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-26.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set Up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          mkdir -p bundle

          git clone --depth 1 https://github.com/mawww/kakoune.git
          (cd kakoune && make -j$(nproc) PREFIX=$(pwd)/../bundle install-strip)

          git clone --depth 1 https://github.com/kak-lsp/kak-lsp.git
          (cd kak-lsp && cargo build --release --locked)

          git clone --depth 1 https://git.sr.ht/~hadronized/kak-tree-sitter
          (cd kak-tree-sitter && cargo build --release --locked)

          git clone --depth 1 https://git.sr.ht/~hadronized/kakoune-tree-sitter-themes

      - name: Bundle
        run: |

          cp kak-lsp/target/release/kak-lsp bundle/bin/
          cp kak-tree-sitter/target/release/kak-tree-sitter bundle/bin/
          cp kak-tree-sitter/target/release/ktsctl bundle/bin/
          mv bundle/share/kak/colors/default.kak bundle/share/kak/colors/original.kak
          cp kakoune-tree-sitter-themes/colors/nightowl/night-owl.kak bundle/share/kak/colors/default.kak

          tar -czvf kakoune-${{ matrix.target }}.tar.gz bundle/

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: kakoune-${{ matrix.target }}.tar.gz
