name: Release Kakoune Bundle

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
            strip: strip -S -x
            data_dir: Library/Application Support
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-26.04-arm
            strip: strip -s
            data_dir: .local/share
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-26.04
            strip: strip -s
            data_dir: .local/share

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set Up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          mkdir -p bundle
          cp LICENSE bundle

          git clone --depth 1 https://github.com/mawww/kakoune.git
          (cd kakoune && make -j$(nproc) PREFIX=$(pwd)/../bundle install)
          ${{ matrix.strip }} bundle/bin/kak

          git clone --depth 1 https://github.com/kak-lsp/kak-lsp.git
          (cd kak-lsp && cargo build --release --locked)
          cp kak-lsp/target/release/kak-lsp bundle/bin/

          git clone --depth 1 https://git.sr.ht/~hadronized/kak-tree-sitter
          (cd kak-tree-sitter && cargo build --release --locked)
          cp kak-tree-sitter/target/release/kak-tree-sitter bundle/bin/

          kts_dir="$HOME/${{ matrix.data_dir }}/kak-tree-sitter"
          mkdir -p "$kts_dir"
          config_path="$kts_dir/config.toml"
          cp kak-tree-sitter-config.toml "$config_path"
          kak-tree-sitter/target/release/ktsctl --config "$config_path" sync \
              bash comment csv fish git-commit go json python sql toml yaml
          mv "$kts_dir" bundle/
          cat python-injections.scm >> $(printf bundle/kak-tree-sitter/queries/python/*/injections.scm)

          git clone --depth 1 https://git.sr.ht/~hadronized/kakoune-tree-sitter-themes
          kts_themes_dir=kakoune-tree-sitter-themes/colors
          colors_dir=bundle/share/kak/colors
          cp "$kts_themes_dir/catppuccin/catppuccin_latte.kak" "$colors_dir/catppuccin-latte.kak"
          cp "$kts_themes_dir/catppuccin/catppuccin_macchiato.kak" "$colors_dir/catppuccin-macchiato.kak"
          cp "$kts_themes_dir/catppuccin/catppuccin_mocha.kak" "$colors_dir/catppuccin-mocha.kak"
          cp "$kts_themes_dir/nightowl/night-owl.kak" "$colors_dir/night-owl.kak"

      - name: Bundle
        run: |
          tar -czvf kakoune-${{ matrix.target }}.tar.gz bundle/

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: kakoune-${{ matrix.target }}.tar.gz
